name: Update RSS Feed

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  update_feed:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      # Step 4: Run the script to update the feed
      - name: Run update_feed.py
        run: |
          python update_feed.py
      # Step 5: Commit and push changes to the repository
      - name: Commit and push updated feed.xml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add feed.xml
          git commit -m "Update feed.xml" || echo "No changes to commit"
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
